command_not_found_handler() {
	# taken from http://www.linuxjournal.com/content/bash-command-not-found
	# - do not run when inside Midnight Commander or within a Pipe
	if [ -n "${MC_SID-}" ] || ! [ -t 1 ]; then
		>&2 echo "$1: command not found"
		return 127
	fi

	toplevel=nixpkgs # should always be available
	cmd=$1
	attrs=$(@out@/bin/nix-locate --minimal --no-group --type x --type s --top-level --whole-name --at-root "/bin/$cmd")
	len=$(echo -n "$attrs" | grep -c "^")

	case $len in
		0)
			>&2 echo "$cmd: command not found"
			;;
		1)
			# if only 1 package provides it auto run the command, will not return
			# 127
			>&2 echo "The program '$cmd' is currently not installed. It is provided by"
			>&2 echo "the package '$toplevel.$atttrs', which is going to be installed now"
			nix-build --no-out-link -A $attrs "<$toplevel>"
			if [ "$?" -eq 0 ]; then
				# nix-shell is weird
				nix-shell -p $attrs --run "$(echo $@)"
				return $?
			else
				>&2 echo "Failed to install $toplevel.attrs.$cmd: command not found"
			fi
			;;
		*)
			>&2 echo "The program '$cmd' is provided by several packages, you can run it via ,(comma)\n or install it manually in ~/.config/home-manager/packages.nix"
			while read attr; do
				>&2 echo", $toplevel.$attr"
			done
			;;
	esac

	return 127
}
